/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bankingsystem;

/**
 *
 * @author Asus
 */
public class CustomerAndAccountManagementWindow extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CustomerAndAccountManagementWindow.class.getName());

    private CustomerDAO customerDAO = new CustomerDAO();
    private AccountDAO accountDAO = new AccountDAO();

    private void loadTableData(String query) {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) Table1.getModel();
        accountDAO.loadCustomerAccountsToTable(model, query);
    }

    /**
     * Creates new form CustomerAndAccountManagementWindow
     */
    public CustomerAndAccountManagementWindow() {
        initComponents();

        javax.swing.table.DefaultTableCellRenderer leftRenderer = new javax.swing.table.DefaultTableCellRenderer();
        leftRenderer.setHorizontalAlignment(javax.swing.JLabel.LEFT);
        leftRenderer.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 5)); // 5px cushion

        // Loop through every column
        for (int i = 0; i < Table1.getColumnCount(); i++) {
            Table1.getColumnModel().getColumn(i).setCellRenderer(leftRenderer);
        }
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundedPanel1 = new studentenrollmentsystem.RoundedPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtFirstName = new studentenrollmentsystem.RoundedTextField();
        txtEmail = new studentenrollmentsystem.RoundedTextField();
        txtLastName = new studentenrollmentsystem.RoundedTextField();
        txtPhoneNumber = new studentenrollmentsystem.RoundedTextField();
        txtBalance = new studentenrollmentsystem.RoundedTextField();
        ComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtSearchBar = new studentenrollmentsystem.RoundedTextField();
        Add = new studentenrollmentsystem.RoundedButton();
        Update = new studentenrollmentsystem.RoundedButton();
        Delete = new studentenrollmentsystem.RoundedButton();
        View = new studentenrollmentsystem.RoundedButton();
        jLabel7 = new javax.swing.JLabel();
        roundedButton1 = new studentenrollmentsystem.RoundedButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Account ID", "First Name", "Last Name", "Email", "Number", "Balance", "Account Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table1);

        jLabel1.setText("Last Name");

        jLabel2.setText("First Name");

        jLabel3.setText("Phone Number");

        jLabel4.setText("Email");

        jLabel5.setText("Initial Balance");

        txtPhoneNumber.addActionListener(this::txtPhoneNumberActionPerformed);

        ComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Savings ", "Current", " " }));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Search ID");

        txtSearchBar.addActionListener(this::txtSearchBarActionPerformed);
        txtSearchBar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchBarKeyReleased(evt);
            }
        });

        Add.setText("Add");
        Add.addActionListener(this::AddActionPerformed);

        Update.setText("Update");
        Update.addActionListener(this::UpdateActionPerformed);

        Delete.setText("Delete");
        Delete.addActionListener(this::DeleteActionPerformed);

        View.setText("View");
        View.addActionListener(this::ViewActionPerformed);

        jLabel7.setText("Acount Type");

        roundedButton1.setText("Verification ");
        roundedButton1.addActionListener(this::roundedButton1ActionPerformed);

        javax.swing.GroupLayout roundedPanel1Layout = new javax.swing.GroupLayout(roundedPanel1);
        roundedPanel1.setLayout(roundedPanel1Layout);
        roundedPanel1Layout.setHorizontalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(roundedPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(roundedPanel1Layout.createSequentialGroup()
                                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(11, 11, 11)
                                        .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(420, 420, 420))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, roundedPanel1Layout.createSequentialGroup()
                                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(98, 98, 98))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel1Layout.createSequentialGroup()
                                        .addGap(176, 176, 176)
                                        .addComponent(Update, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(53, 53, 53)))
                                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                                        .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(69, 69, 69)
                                        .addComponent(View, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel1Layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(roundedPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(ComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(roundedPanel1Layout.createSequentialGroup()
                                                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(15, 15, 15)))
                                                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(58, 58, 58))
                                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                                        .addGap(177, 177, 177)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtSearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel1Layout.createSequentialGroup()
                .addComponent(roundedButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        roundedPanel1Layout.setVerticalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(19, 19, 19)
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(39, 39, 39)
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(View, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Update, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(txtSearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roundedButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roundedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roundedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneNumberActionPerformed

    private void txtSearchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchBarActionPerformed
        // TODO add your handling code here:
        String search = txtSearchBar.getText();
        loadTableData(search);
    }//GEN-LAST:event_txtSearchBarActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
       int selectedRow = Table1.getSelectedRow();
    if (selectedRow >= 0) {
        // Grab the Account ID (which is now Column 0)
        int accountId = (int) Table1.getValueAt(selectedRow, 0);
        
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Delete this customer and their account?", "Confirm", javax.swing.JOptionPane.YES_NO_OPTION);
        
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            
            //  Find the Customer ID using the Account ID 
            int customerId = -1;
            try (java.sql.Connection conn = DBConnection.getConnection(); 
                 java.sql.PreparedStatement stmt = conn.prepareStatement("SELECT customer_id FROM Account WHERE account_id = ?")) {
                 stmt.setInt(1, accountId);
                 java.sql.ResultSet rs = stmt.executeQuery();
                 if(rs.next()) customerId = rs.getInt("customer_id");
            } catch(Exception e) { 
                 e.printStackTrace(); 
            }
            // ------------------------------------------------------

            if (customerId != -1) {
                customerDAO.deleteCustomer(customerId);
                javax.swing.JOptionPane.showMessageDialog(this, "Deleted successfully!");
                loadTableData(""); // Refresh table
                clearFields();     // Clears the text fields
            }
        }
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select a row to delete.");
    }
    }//GEN-LAST:event_DeleteActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:

   // Get all the text and trim spaces
    String fName = txtFirstName.getText().trim();
    String lName = txtLastName.getText().trim();
    String email = txtEmail.getText().trim();
    String phone = txtPhoneNumber.getText().trim();
    String balanceText = txtBalance.getText().trim();
    String type = ComboBox1.getSelectedItem().toString().trim();

    // EMPTY FIELD VALIDATION CHECK 
    if (fName.isEmpty() || lName.isEmpty() || email.isEmpty() || phone.isEmpty() || balanceText.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please fill out all fields before adding!", "Missing Information", javax.swing.JOptionPane.WARNING_MESSAGE);
        return; 
    }
    
    try {
        double balance = Double.parseDouble(balanceText);
        
        // ONE-TO-MANY RELATIONSHIP 
        int selectedRow = Table1.getSelectedRow();
        int customerId = -1;

        // If you clicked a row, find out who that person is!
        if (selectedRow >= 0) {
            int selectedAccountId = (int) Table1.getValueAt(selectedRow, 0); 
            
            try (java.sql.Connection conn = DBConnection.getConnection(); 
                 java.sql.PreparedStatement stmt = conn.prepareStatement("SELECT customer_id FROM Account WHERE account_id = ?")) {
                 stmt.setInt(1, selectedAccountId);
                 java.sql.ResultSet rs = stmt.executeQuery();
                 if(rs.next()) customerId = rs.getInt("customer_id");
            } catch(Exception e) { 
                 e.printStackTrace(); 
            }
        }

        // Process the Database Add
        if (customerId != -1) {
            // -------------------------------------------------------------
            // EXISTING CUSTOMER: Add a new account to the same person!
            // -------------------------------------------------------------
            
            // 1. Update their info just in case you changed their phone/email
            customerDAO.updateCustomer(customerId, fName, lName, email, phone);
            
            // 2. Add the NEW account to the SAME customer
            accountDAO.addAccount(customerId, type, balance);
            
            javax.swing.JOptionPane.showMessageDialog(this, "New Account added to existing Customer successfully!");
            
        } else {
            // -------------------------------------------------------------
            // BRAND NEW CUSTOMER: Create both Customer and Account
            // -------------------------------------------------------------
            customerId = customerDAO.addCustomer(fName, lName, email, phone);
            if (customerId != -1) {
                accountDAO.addAccount(customerId, type, balance);
                javax.swing.JOptionPane.showMessageDialog(this, "New Customer and Account added successfully!");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Failed to add customer.", "Database Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        // Refresh table and clear everything (which deselects the row automatically)
        loadTableData(""); 
        clearFields();     

    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter a valid number for the balance.", "Invalid Input", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_AddActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
       // 1. Get all the text and remove accidental extra spaces using .trim()
  int selectedRow = Table1.getSelectedRow();
    
    // Make sure a row is actually clicked!
    if (selectedRow < 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select a row from the table to update!", "No Row Selected", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 1. Get all the text
    String fName = txtFirstName.getText().trim();
    String lName = txtLastName.getText().trim();
    String email = txtEmail.getText().trim();
    String phone = txtPhoneNumber.getText().trim();
    String balanceText = txtBalance.getText().trim();
    String type = ComboBox1.getSelectedItem().toString().trim();

    // 2. Prevent empty fields
    if (fName.isEmpty() || lName.isEmpty() || email.isEmpty() || phone.isEmpty() || balanceText.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please fill out all fields before updating!", "Missing Information", javax.swing.JOptionPane.WARNING_MESSAGE);
        return; 
    }

    try {
        double balance = Double.parseDouble(balanceText);
        
        // Get the Account ID from the table (Column 0)
        int selectedAccountId = (int) Table1.getValueAt(selectedRow, 0); 
        
        // Find the Customer ID secretly attached to this account
        int customerId = -1;
        try (java.sql.Connection conn = DBConnection.getConnection(); 
             java.sql.PreparedStatement stmt = conn.prepareStatement("SELECT customer_id FROM Account WHERE account_id = ?")) {
             stmt.setInt(1, selectedAccountId);
             java.sql.ResultSet rs = stmt.executeQuery();
             if(rs.next()) customerId = rs.getInt("customer_id");
        } catch(Exception e) { 
             e.printStackTrace(); 
        }

        if (customerId != -1) {
            // 3. UPDATE BOTH TABLES!
            customerDAO.updateCustomer(customerId, fName, lName, email, phone); // Updates the Customer table
            accountDAO.updateAccount(selectedAccountId, type, balance);         // Updates the Account table
            
            javax.swing.JOptionPane.showMessageDialog(this, "Record updated successfully!");
            
            // Refresh table and clear text fields
            loadTableData(""); 
            clearFields();     
        }

    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter a valid number for the balance.", "Invalid Input", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_UpdateActionPerformed

    private void ViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewActionPerformed
        // TODO add your handling code here:
        loadTableData("");
        clearFields();
        txtSearchBar.setText("");
    }//GEN-LAST:event_ViewActionPerformed

    private void txtSearchBarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchBarKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_txtSearchBarKeyReleased

    private void Table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table1MouseClicked
        // TODO add your handling code here:
       int selectedRow = Table1.getSelectedRow();
    
    if (selectedRow >= 0) {
        // Sequential mapping matching the new 7-column order
        String firstName = Table1.getValueAt(selectedRow, 1) != null ? Table1.getValueAt(selectedRow, 1).toString() : "";
        String lastName = Table1.getValueAt(selectedRow, 2) != null ? Table1.getValueAt(selectedRow, 2).toString() : "";
        String email = Table1.getValueAt(selectedRow, 3) != null ? Table1.getValueAt(selectedRow, 3).toString() : "";
        String phone = Table1.getValueAt(selectedRow, 4) != null ? Table1.getValueAt(selectedRow, 4).toString() : "";
        String balance = Table1.getValueAt(selectedRow, 5) != null ? Table1.getValueAt(selectedRow, 5).toString() : "";
        String accountType = Table1.getValueAt(selectedRow, 6) != null ? Table1.getValueAt(selectedRow, 6).toString() : "";
        
        // Populate the text fields
        txtFirstName.setText(firstName);
        txtLastName.setText(lastName);
        txtEmail.setText(email);
        txtPhoneNumber.setText(phone);
        txtBalance.setText(balance);
        ComboBox1.setSelectedItem(accountType);
    }
    }//GEN-LAST:event_Table1MouseClicked

    private void roundedButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundedButton1ActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(() -> new TransactionManagementWindow().setVisible(true));
        this.dispose();
    }//GEN-LAST:event_roundedButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CustomerAndAccountManagementWindow().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private studentenrollmentsystem.RoundedButton Add;
    private javax.swing.JComboBox<String> ComboBox1;
    private studentenrollmentsystem.RoundedButton Delete;
    private javax.swing.JTable Table1;
    private studentenrollmentsystem.RoundedButton Update;
    private studentenrollmentsystem.RoundedButton View;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private studentenrollmentsystem.RoundedButton roundedButton1;
    private studentenrollmentsystem.RoundedPanel roundedPanel1;
    private studentenrollmentsystem.RoundedTextField txtBalance;
    private studentenrollmentsystem.RoundedTextField txtEmail;
    private studentenrollmentsystem.RoundedTextField txtFirstName;
    private studentenrollmentsystem.RoundedTextField txtLastName;
    private studentenrollmentsystem.RoundedTextField txtPhoneNumber;
    private studentenrollmentsystem.RoundedTextField txtSearchBar;
    // End of variables declaration//GEN-END:variables
// Custom method to clear all text fields and reset selections
    private void clearFields() {
        txtFirstName.setText("");
        txtLastName.setText("");
        txtEmail.setText("");
        txtPhoneNumber.setText("");
        txtBalance.setText("");
        ComboBox1.setSelectedIndex(0); // Resets dropdown to the first option
        Table1.clearSelection(); // Deselects the row in the table
    }
}
